matrix:
    include:
        - language: node_js
          node_js:
              - 12
          before_script:
              - cd frontend
          script:
              - npm ci
              - npm run build:ci

        - language: python
          python: 3.8.0
          install:
              - pip install -r requirements.txt
              - wget -O tika-server.jar http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server/1.24/tika-server-1.24.jar
              - python -c "import nltk; nltk.download('all')"
              - python -m spacy download de_core_news_sm
          script:
              - python -m unittest discover -s tests
