matrix:
    include:
        - language: node_js
          node_js:
              - 12
          before_script:
              - cd frontend
          script:
              - npm ci
              - npm run build:ci

        - language: python
          python: 3.8.0
          install:
              - pip install -r requirements.txt
          script:
              - python -c "import nltk; nltk.download('all')"
              - python -m unittest discover -s tests
